### ISSUE TITLE
Add support for sending a batch of queries to NameRes simultaneously 

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/NameResolution#110]
This would allow people to bulk-request names from NameRes.

**Comment by gloriachin** [comment]
Would be very useful when new KGs come.

**Comment by gaurav** [comment]
This is now in development, and an early form is up at https://name-resolution-sri.renci.org/docs#/lookup/bulk_lookup_bulk_lookup_post

**Comment by gaurav** [comment]
This is now up at Translator CI (https://name-lookup.ci.transltr.io/docs#/lookup/bulk_lookup_bulk_lookup_post), so I'll go ahead and close it. It'll be pushed up to Test and Prod once we restart Translator releases in the new funding cycle.
