### ISSUE TITLE
Chemical synonym not recognized

### ISSUE THREAD

**Issue by karafecho** [TranslatorSRI/NameResolution#122]
This issue is to report that Name Resolver was unable to recognize the chemical indole-3-carbinol, which ChEBI considers to be a synonym of indole-3-methanol, id CHEBI:24814 (https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:24814). This caused a user to mistakenly believe that ROBOKOP and Translator did not have any information on indole-3-carbinol.

**Comment by gaurav** [comment]
Thanks for reporting this, Kara! I'm seeing `indole-3-carbinol` return PUBCHEM.COMPOUND:3712 on both [NameRes Prod](https://name-lookup.transltr.io/lookup?string=indole-3-carbinol&offset=0&limit=10) as well as [NameRes Dev](https://name-resolution-sri.renci.org/lookup?string=indole-3-carbinol&offset=0&limit=10), and both of them are merged with CHEBI:24814 on both [NodeNorm Prod](https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=CHEBI%3A24814&conflate=true) and [NodeNorm Dev](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=CHEBI%3A24814&conflate=true&drug_chemical_conflate=false&description=false). Are these two identifiers not supposed to be merged?
