### ISSUE TITLE
Use clique size in scoring?

### ISSUE THREAD

**Issue by cbizon** [TranslatorSRI/NameResolution#124]
Consider "Pain".  There are 2 cliques:
EFO:0003843 and HP:0012531.

The EFO is returned first but the HP merges a bunch of stuff (EFO is by itself).

Should the clique size be used in scoring?  all else being equal, I'd rather get the larger clique...  And it might be a way to naturally prefer better-acting curies to a bunch of random UMLS dross.

**Comment by gaurav** [comment]
We now [boost by the log of the clique identifier count](https://github.com/TranslatorSRI/NameResolution/blob/9b18de125eb215e9c5ed7c88429cc01dce88dec3/api/server.py#L391-L395). This seems to do a better job than boosting with the count itself or setting up tiered boosting (e.g. no boost under 5, 2x from 6-10, 3x for 10+). Closing.
