### ISSUE TITLE
How do you get synonyms JSON file from the download TSV files?

### ISSUE THREAD

**Issue by vemonet** [TranslatorSRI/NameResolution#137]
The workflow to load Babel TSV data to SOLR is missing a crucial step: converting the TSV to JSON files (containing more info than the TSV, e.g. pref label and type)

In the Makefile we can see there is step 1 to download the TSV:
https://github.com/TranslatorSRI/NameResolution/blob/master/data-loading/Makefile#L32

Step 2 is missing (probably the step that generates JSON and enrich the data_

Step 3 is solr starting, step 4 is loading the JSON files

Any idea where I could find this step?

**Comment by gaurav** [comment]
My apologies, @vemonet -- I just forgot to update that URL, which is pointing to the previous release of the synonym files in a JSON format. I've just updated the URL to https://stars.renci.org/var/babel_outputs/2023nov5/synonyms/, which has the synonym files in the new JSON format (PR #139). Please let me know if you run into any problems with running this script and Docker image!

**Comment by gaurav** [comment]
Closed by #139.
