### ISSUE TITLE
Not returning expected CURIE

### ISSUE THREAD

**Issue by karafecho** [TranslatorSRI/NameResolution#27]
This issue is to report a missing CURIE. Specifically, ICEES KG calls Name Resolver to map CURIEs to ICEES feature variable, using `search_term` and `limit` parameters. For diseases, we have been using search terms structured as 'disease X diagnosis'. This approach was tested extensively and has been yielding more accurate mappings with less noise. However, in our latest ICEES KG instance, 'asthma diagnosis' was not correctly mapped to MONDO:0004979, which was not the case previously, at least I don't think so, given that I've successfully used that CURIE in numerous queries. I tested several other "search terms" using Name Resolver and these return the expected CURIES (see example below). So, I believe the issue is specific to "asthma diagnosis" and MONDO:0004979.

Example returns for "idiopathic bronchiectasis diagnosis":

```
{
  "MONDO:0018956": [
    "Idiopathic bronchiectasis (diagnosis)",
    "idiopathic bronchiectasis",
    "bronchiectasis idiopathic",
    "Idiopathic bronchiectasis",
    "Idiopathic bronchiectasis (disorder)"
  ]
}
```

**Comment by gaurav** [comment]
This looks like it is working well on both the RENCI NameRes instances (Dev and Exp). @karafecho could you please confirm, and close this issue if it appears to be fixed? If not, let me know and I'll investigate it further!

**Comment by karafecho** [comment]
Confirmed. Closing issue.
