### ISSUE TITLE
Add GET method for `/lookup`

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/NameResolution#29]
Currently, `/lookup` is a POST-only endpoint. If it could also be used via a GET request, this would make it easier to link to a particular query.

**Comment by gaurav** [comment]
When we fix this, it would probably be nice to change landing page at https://name-resolution-sri.renci.org/ to be something other than `{"detail":"Not Found"}`.

**Comment by andrewsu** [comment]
just adding a +1 to this ticket...

**Comment by gaurav** [comment]
Fixing this would make it much easier to discuss issues like https://github.com/NCATSTranslator/Feedback/issues/301, which stem from incorrect NameRes search results.
