### ISSUE TITLE
Figure out why NameRes is showing up as a TRAPI endpoint on SmartAPI

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/NameResolution#31]
This appears to be because the URL https://trapi-openapi.apps.renci.org/utility/infores%3Asri-name-resolver?version=%2A has been registered in SmartAPI as https://smart-api.info/registry?q=9995fed757acd034ef099dbb483c4c82, and is therefore displayed in the [ARAX SmartAPI list](https://arax.ncats.io/beta/?smartapi=1) -- note this only has the `translator` tag, just like the actual [NameRes production OpenAPI](https://name-lookup.transltr.io/openapi.json), but it's possible the "TRAPI vQuality" in the title might be cause ARAX to think that this is a TRAPI endpoint.

**Comment by YaphetKG** [comment]
(Trapi vUtility) is now removed from the title of name resolution.

**Comment by gaurav** [comment]
Thanks, Yaphet! That seems to have removed them from the list at https://arax.ncats.io/beta/?smartapi=1 -- I'll check with Eric and see if we're good to close this issue.
