### ISSUE TITLE
TS.5.c: Prototype name resolution services - broaden scope

### ISSUE THREAD

**Issue by mmersmann** [TranslatorSRI/NameResolution#4]
Broaden scope to include chemicals.

Related:
[TS.5: Prototype name resolution services](https://github.com/TranslatorIIPrototypes/NameResolution/issues/1)
[TS.5.a: Prototype name resolution services - synonym files](https://github.com/TranslatorIIPrototypes/NameResolution/issues/2)
[TS.5.b: Prototype name resolution services - infrastructure](https://github.com/TranslatorIIPrototypes/NameResolution/issues/3)

**Comment by gaurav** [comment]
I think we include chemicals now. Is there anything else we need to do in this issue?

**Comment by gaurav** [comment]
I'm going to close this issue since we have chemicals now (maybe... too many chemicals), but please reopen if I've missed anything.
