### ISSUE TITLE
Add the canonical label and Biolink type to NameRes results

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/NameResolution#43]
At the moment, the Translator UI queries NameRes to find identifiers to display, then queries NodeNorm for the canonical label, Biolink type and other information. Both the canonical label and the Biolink type (as needed for #39 anyway) would be great to include in the NodeNorm results so that a second NodeNorm query is not needed.

**Comment by cbizon** [comment]
Of course the downside here is that it makes the solr documents even that much bigger

**Comment by gaurav** [comment]
> If we need to add the type and preferred name to every element, then oof.

The other option would be for NameRes to include a Redis table that has id to canonical name + biolink type mappings, but that would complicate the backend.

> I wonder if we could transform the docs to something more like

I like this! NameRes is loaded from the synonym file, which is currently in the format:
> id [tab] synonym type [tab] synonym

I think we if modify this to:
> id [tab] biolink type [tab] canonical label [tab] synonym type [tab] synonym

We could use [Solr updates](https://solr.apache.org/guide/6_6/updating-parts-of-documents.html) to load it in the format you suggest. The synonym files would then get much larger, but the Solr database -- which is the piece we have to transfer from RENCI to ITRB -- might end up being smaller because it has fewer documents in it.

Is it okay to drop the `length` field? Is it currently being used?

**Comment by cbizon** [comment]
I think it is being used to order the synonyms when they get grouped by curie.   But I think if we put all the names in one document we wouldn't need to do that (and could therefore lose it).  I think that it's worth giving this a shot and seeing whether it works or not.
