### ISSUE TITLE
1,2,3-benzenetriol sulfate doesn't work, but benzenetriol sulfate does

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/NameResolution#57]

**Comment by EvanDietzMorris** [comment]
It doesn't seem to be the commas that are the issue, "3-benzenetriol sulfate" returns nothing as well.

**Comment by gaurav** [comment]
It works! https://name-resolution-sri.renci.org/lookup?string=1%2C2%2C3-benzenetriol%20sulfate&offset=0&limit=10

Closing.
