### ISSUE TITLE
Offset gives 500

### ISSUE THREAD

**Issue by cbizon** [TranslatorSRI/NameResolution#58]
Query any term, and set the offset higher than the number of results causes a 500.

**Comment by gaurav** [comment]
This looks like it's fixed in [dev](http://name-resolution-sri-dev.apps.renci.org/docs), which returns an empty list instead. I'll keep this open until we deploy it.

**Comment by gaurav** [comment]
This is definitely fixed in Dev now: https://name-resolution-sri.renci.org/lookup?string=acetaminophen&offset=5000&limit=10

It's also fixed in Prod: https://name-lookup.transltr.io/lookup?string=acetaminophen&offset=5000&limit=10

Closing.
