### ISSUE TITLE
`Fluphenazine Decanoate Injection, USP` should match fluphenazine decanoate injection (UMLS:C2355623)

### ISSUE THREAD

**Issue by vemonet** [TranslatorSRI/NameResolution#59]
`Fluphenazine Decanoate Injection, USP` does not match due to `, USP` being added at the end (which is a common alternative to the label)

Removing `, USP` makes it match to UMLS:C2355623

**Comment by gaurav** [comment]
This works now! https://name-resolution-sri.renci.org/lookup?string=Fluphenazine%20Decanoate%20Injection%2C%20USP&offset=0&limit=10

Closing, but please reopen if there's anything here I'm missing.
